name: CI

on:
  push:
    branches: [ "*" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/esphome/esphome

    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: |
          ls -al
          which esphome
