name: CI

on:
  push:
    branches: [ "*" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/esphome/esphome:2024.7.3

    steps:
      - uses: actions/checkout@v4
      - name: Test Config
        run: |
          esphome config radiator-fan-controller.yml

      - name: Build Firmware
        run: |
          esphome compile radiator-fan-controller.yml

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: smart-radiator-fan-controller
          path: .esphome/build/smart-radiator-fan-controller/.pioenvs/smart-radiator-fan-controller/firmware.factory.bin
